version: "3.7"
services:
  nginxexamenportal:
    image: nginx
    container_name: nginxexamenportal
    ports:
      - "94:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src:/src
      - ./logs/:/var/log/nginx/
    networks:
      default:
        aliases:
          - nginxexamenportal
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
  phpexamenportal:
    build:
      context: .
      dockerfile: dockerfile
    container_name: phpexamenportal
    volumes:
      - ./src:/src
    working_dir: /src
    ports:
      - 9004:8000
    networks:
      default:
         aliases:
          - phpexamenportal
  
networks:
  default: